version: '3.8'
volumes:
  pgdata: {}
  pglatestdata: {}
services:
  # STORAGES
  postgresql:
    build: ./postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      # host_port:container_port
      - 5555:5432
    restart: unless-stopped
    volumes:
      # host_dir:container_dir
      - pgdata:/var/lib/postgresql/data